install.packages("adegenet")
install.packages("poppr")
install.packages("hierfstat")
install.packages("diveRsity")
install.packages("vegan")
install.packages("ape")
install.packages("ade4")
install.packages("pegas")
install.packages("ggplot2")
install.packages("locfit")
source("https://bioconductor.org/biocLite.R")
biocLite("edgeR")
biocLite("goseq")
biocLite("VariantAnnotation")
biocLite("qvalues")

