install.packages("adegenet")
install.packages("poppr")
install.packages("hierfstat")
install.packages("diveRsity")
install.packages("vegan")
install.packages("ape")
install.packages("ade4")
install.packages("pegas")
install.packages("ggplot2")
install.packages("locfit")
source("https://bioconductor.org/biocLite.R")
biocLite("edgeR")
biocLite("goseq")
biocLite("VariantAnnotation")
biocLite("qvalues")


require("adegenet")
require("poppr")
require("hierfstat")
require("diveRsity")
require("vegan")
require("ape")
require("ade4")
require("pegas")
require("ggplot2")
require("locfit")
require("edgeR")
require("goseq") #erro de dependencia
require("VariantAnnotation")
require("qvalue")
